{% set name = "hydromt_wflow" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydromt_wflow-{{ version }}.tar.gz
  sha256: 7d90f1879c002024a55a12f831458763694905344b285391e9204dcdc5b6e79d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.9
  run:
    - dask
    - geopandas >=0.10
    - hydromt >=0.9.3,<0.10
    - netcdf4
    - numpy
    - pandas
    - pyflwdir >=0.5.7
    - pyproj
    - python >=3.9
    - rioxarray
    - scipy
    - shapely
    - toml
    - universal_pathlib <0.2
    - xarray

test:
  imports:
    - hydromt_wflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/hydromt_wflow/
  summary: hydroMT plugin for wflow models.
  dev_url: https://github.com/Deltares/hydromt_wflow
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalmijn
    - JoostBuitink
    - DirkEilander
    - hboisgon
