{% set name = "hydromt_wflow" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydromt_wflow-{{ version }}.tar.gz
  sha256: b513e795011859e053a677c6789b74eac704286b0ab814b2fb33ce6eff83e487

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.8
  run:
    - dask
    - geopandas >=0.8
    - hydromt >=0.4.0
    - netcdf4
    - numpy
    - pandas
    - pyflwdir >=0.4.7
    - pygeos
    - python >=3.8
    - rasterio
    - scipy
    - toml
    - xarray

test:
  imports:
    - hydromt_wflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/hydromt_wflow/
  summary: hydroMT plugin for wflow models.
  dev_url: https://github.com/Deltares/hydromt_wflow
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DirkEilander
    - hboisgon
